[package]
name = "arbitrage-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
uniswap-v3-sdk = { version = "2.2.0", features = ["extensions", "std"] }
uniswap-sdk-core = "3.0.0"
eyre = "0.6.12"
