[workspace]

resolver = "2"
members = ["analyse", "pools"]

[workspace.dependencies]
uniswap-v3-sdk = { version = "2.2.0", features = ["extensions", "std"] }
uniswap-sdk-core = "3.0.0"
eyre = "0.6.12"
