[package]
name = "rbtr"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = { workspace = true }
serde = { workspace = true }
eyre = { workspace = true }
alloy = { workspace = true }
tokio = { workspace = true }
tokio-util = "0.7.12"
actix = "0.13.5"
ctrlc = "3.1.0"

lib = { path = "../../crates/lib" }
